# frozen_string_literal: true
source 'https://rubygems.org'

gem 'activesupport'
gem 'aruba'
gem 'cucumber'
gem 'factory_girl'
gem 'faker'
gem 'gli'
gem 'phut', github: 'trema/phut', branch: 'develop'
gem 'pio'
gem 'rake'
gem 'rspec'
gem 'rspec-expectations'
gem 'rspec-given'
gem 'rubocop'
gem 'trema'
